export enum CrimeTypes {
  ALLCRIME = 'ALLCRIME',

  ANTISOCIALBEHAVIOUR = 'ANTISOCIALBEHAVIOUR',

  BICYCLETHEFT = 'BICYCLETHEFT',

  BURGLARY = 'BURGLARY',

  CRIMINALDAMAGEARSON = 'CRIMINALDAMAGEARSON',

  DRUGS = 'DRUGS',

  OTHERTHEFT = 'OTHERTHEFT',

  POSSESSIONOFWEAPONS = 'POSSESSIONOFWEAPONS',

  PUBLICORDER = 'PUBLICORDER',

  ROBBERY = 'ROBBERY',

  SHOPLIFTING = 'SHOPLIFTING',

  THEFTFROMTHEPERSON = 'THEFTFROMTHEPERSON',

  VEHICLECRIME = 'VEHICLECRIME',

  VIOLENCEANDSEXUALOFFENCES = 'VIOLENCEANDSEXUALOFFENCES',

  OTHERCRIME = 'OTHERCRIME',
}
